drinks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from drinks.views import Login, home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="homepage"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('menu/', include("menu.urls")),
    ]

menu/urls.py
from django.urls import path

from menu.views import DrinkTypeDetailView, DrinkTypeListView, DrinkTypeCreateView, DrinkTypeUpdateView, DrinkTypeDeleteView

app_name = "menu"


urlpatterns = [
    path(
        "types/",
        DrinkTypeListView.as_view(),
        name="types_list"
    ),
    path(
        "type/<int:pk>/",
         DrinkTypeDetailView.as_view(),
         name="type_detail"
    ),
    path(
        "new_type/",
        DrinkTypeCreateView.as_view(),
        name="new_type"
    ),
    path(
        "type/<int:pk>/update/",
        DrinkTypeUpdateView.as_view(),
        name="edit_type"
    ),
    path(
    "type/<int:pk>/delete/",
    DrinkTypeDeleteView.as_view(),
    name="delete_type"
    ),
]

menu/models.py
from django.db import models

# Create your models here.

class DrinkType(models.Model):

    name = models.CharField(max_length=255)
    description = models.TextField()


class Drink(models.Model):

    name = models.CharField(max_length=255)
    description = models.TextField()

    typ = models.ForeignKey(DrinkType, on_delete=models.PROTECT, related_name="drinks")

drinks/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView

from django.shortcuts import render

__all__ = ["home","Login"]


def home(request):
    return render(request, "home.html")


class Login(LoginView):
    authentication_form = AuthenticationForm
    template_name = "authentication/login.html"

menu/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from django.utils.decorators import method_decorator
from menu.models import DrinkType

__all__ = [
    "DrinkTypeCreateView",
    "DrinkTypeDelete.View"
    "DrinkTypeDetailView",
    "DrinkTypeListView",
    "DrinkTypeUpdateView",
]


class DrinkTypeListView(ListView):
    model = DrinkType


class DrinkTypeDetailView(DetailView):
    model = DrinkType


@method_decorator(login_required, name="dispatch")
class DrinkTypeCreateView(CreateView):
    model = DrinkType
    fields = ("name", "description")

    success_url = reverse_lazy("menu:types_list")


@method_decorator(login_required, name="dispatch")
class DrinkTypeUpdateView(UpdateView):
    model = DrinkType
    fields = ("name", "description")

    def get_success_url(self):
        return reverse_lazy(
            "menu:type_detail",
            kwargs={"pk": self.object.id}
        )

@method_decorator(login_required, name="dispatch")
class DrinkTypeDeleteView(DeleteView):
    model = DrinkType

    success_url = reverse_lazy('menu:types_list')

menu/templates/menu/drinktype_confirmdelete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Confirm elimination</h1>

<p>
    <a href="{% url 'menu:types_list' %}">
        Annulla / Torna indietro
    </a>
</p>
<p>Confirm type elimination "{{ object.name }}"</p>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm">
</form>

{% endblock %}

menu/templates/menu/drinktype_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Type {{ object.id }}: {{object.name}}</h1>

<p>
    <a href="{% url 'menu:types_list' %}">
       Go back to drinks' list
    </a>
</p>

<p>{{ object.description }}</p>

<hr>
<ul>
    {% for el in object.drinks.all %}
         <li>{{ el.name }}</li>
    {% endfor %}
</ul>
{% endblock %}

menu/templates/menu/drinktype_form.html
{% extends "base.html" %}

{% block content %}
<h1>Types list</h1>


<p>
    <a href="{% url 'menu:types_list' %}">
        Annulla / Torna indietro
    </a>
</p>

<form action="" method="post">
    {% csrf_token %}

    {{ form | crispy }}

    <input type="submit" value="Salva">
</form>

{% endblock %}

menu/templates/menu/drinktype_list.html
{% extends "base.html" %}

{% block content %}
<h1>Lista di Categorie</h1>


{% for el in object_list %}
    <p>
        {{ el.id }}) {{ el.nome }} -
        <a href="{% url 'menu:type_detail' el.id %}">
            Visualizza dettaglio
        </a>
        (
        <a href="{% url 'menu:edit_type' el.id %}">
            Modifica
        </a>
        -
        <a href="{% url 'menu:delete_type' el.id %}">
            Elimina
        </a>
        )
    </p>
{% endfor %}

<hr>

<p>
    <a href="{% url 'menu:new_type' %}">
        Crea nuova
    </a>
</p>

{% endblock %}

templates/authentication/login.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Effettua il login</h1>

<form action="" method="post">
    {% crispy form %}

    <input type="submit" value="Login">
</form>

{% endblock %}

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Il mio sito bellissimo</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
    <nav class="container navbar">
        <a href="{% url 'homepage' %}" class="nav-item">Home</a>
        |
        <a href="{% url 'menu:types_list' %}" class="nav-item">Categorie di Cibo</a>
        |
        {% if user.is_anonymous %}
            <a href="{% url 'login' %}" class="nav-item">Login</a>
        {% else %}
            <a href="{% url 'logout' %}" class="nav-item">Logout</a>
        {% endif %}
    </nav>
    <hr>
    {% if user.is_authenticated %}
        <p class="container">
            Ciao {{ user.username }}!
        </p>
    {% endif %}
    <main class="container">
      {% block content %}
        Contenuto di default - da sovrascrivere
      {% endblock %}
    </main>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome!</h1>
<p>Questa è la Home</p>
<p>Lorem ipsum</p>
{% endblock %}